# Generated by Django 6.0.3 on 2026-04-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('dthr_evento', models.DateTimeField()),
                ('responsavel', models.CharField(max_length=100)),
                ('duracao', models.IntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
