# Generated by Django 6.0.3 on 2026-04-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_local', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('descricao_esporte', models.TextField(max_length=500)),
                ('disponivel', models.BooleanField(default=True)),
                ('dias_disponiveis', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
