# Generated by Django 6.0.3 on 2026-04-17 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carro_garagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garagem',
            name='carros',
        ),
        migrations.AddField(
            model_name='carro',
            name='garagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.garagem'),
        ),
        migrations.AddField(
            model_name='garagem',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='garagem',
            name='observacoes',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Hatch', 'Hatch'), ('SUV', 'SUV')], max_length=100),
        ),
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='garagem',
            name='capacidade',
            field=models.IntegerField(default=10),
        ),
    ]
